# -*- coding: utf-8 -*-
# Generated by Django 2.2 on 2019-12-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0003_block_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Blocked Relationship', 'verbose_name_plural': 'Blocked Relationships'},
        ),
        migrations.AddField(
            model_name='follow',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
